mypopen_mypclose: mypopen.c File Reference
mypopen.c File Reference
#include "mypopen.h"
Functions
FILE * mypopen (const char *command, const char *type)
int mypclose (FILE *stream)
static void childAction (int fd[2], int unused_end, int used_end, const char *command, int fileno)
static FILE * parentAction (int fd[2], int unused_end, int used_end, const char *type)
Variables
static FILE * fp = NULL
static pid_t childpid
Detailed Description
mypopen_mypclose Beispiel 2
Author:
Karin Kalman <karin.kalman@technikum-wien.at>
Michael Mueller <michael.mueller@technikum-wien.at>
Gerhard Sabeditsch <gerhard.sabeditsch@technikum-wien.at>
Date:
2016/04/17
Version:
Revision
2
URL: $HeadURL$
Last Modified:
Author
Gerhard
Definition in file mypopen.c.
Function Documentation
static void childAction (int fd[2], int unused_end, int used_end, const char * command, int fileno) [static]
-------------------------------------------------------------- help - functions -- static void childAction(int fd[2], int unused_end, int used_end, const char *command) FUNCTION is only for the CHILD PROCESS: -this function link the used file descriptor with the parent process stdout -this function also close the unused file descriptor -this function executes the given command in a normal shell like popen
Definition at line 182 of file mypopen.c.
Referenced by mypopen().
int mypclose (FILE * stream)
-------------------------------------------------------------- mypclose -function --
Definition at line 110 of file mypopen.c.
References childpid, and fp.
FILE* mypopen (const char * command, const char * type)
-------------------------------------------------------------- mypopen -function --
Open new pipe
return value fd[0] is for reading
return value fd[1] is for writing
if fork() is successful it return twice:
in parent process the return value is the process id (PID) of the childprocess
in child process the return value is 0
Child process
Parent process
Definition at line 33 of file mypopen.c.
References childAction(), childpid, fp, parentAction(), READ_END, and WRITE_END.
static FILE* parentAction (int fd[2], int unused_end, int used_end, const char * type) [static]
static FILE * parentAction(int fd[2], int unused_end, int used_end, const char *type) FUNCTION is only for the PARENT PROCESS: -this function link the used file descriptor with the parent process stin -this function also close the unused file descriptor -this function convert the used filedescriptor into a filepointer and returns the filepointer
Definition at line 210 of file mypopen.c.
Referenced by mypopen().
Variable Documentation
pid_t childpid [static]
Definition at line 28 of file mypopen.c.
Referenced by mypclose(), and mypopen().
FILE* fp = NULL [static]
-------------------------------------------------------------- includes -- -------------------------------------------------------------- global static variables --
Definition at line 27 of file mypopen.c.
Referenced by mypclose(), and mypopen().